apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus
  name: prometheus-flaskapp-monitoring
spec:
  endpoints:
  - interval: 30s
    port: web
    path: /metrics
  selector:
    matchLabels:
      app: {{ .Values.appName }}