apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.Name }}
spec:
  accessModes:
  - {{ .Values.accessMode }} 
  resources:
    requests:
      storage: {{ .Values.pvc.Storage }}
  storageClassName: ""