apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.serviceName }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.appName }}
  ports:
  - name: web
    port: 80
    targetPort: 8080
  
  
